name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: cargo build --workspace

    - name: Test
      run: PATH="$PWD/target/debug:$PATH" cargo test --lib --workspace
